### ISSUE TITLE
new issue to test new flow version

### ISSUE THREAD

**Issue by jaykchen** [jaykchen/vitesse-lite#14]
just to test issue getting

**Comment by jaykchen** [comment]
this is a comment

**Comment by jaykchen** [comment]
switched back to text davincci model

**Comment by jaykchen** [comment]
davinci wasn't commissioned last time

**Comment by jaykchen** [comment]
forgot to auth for api last time

**Comment by jaykchen** [comment]
what is completionrequest?

**Comment by jaykchen** [comment]
where is the problem?

**Comment by amiiiiii830** [comment]
I was kidding
